apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: historia-clinicas-ssl
  namespace: historia-clinicas
spec:
  domains:
    - hc.yo-soy.co
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: historia-clinicas-ingress
  namespace: historia-clinicas
  labels:
    app.kubernetes.io/name: historia-clinicas
    app.kubernetes.io/managed-by: argocd
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "historia-clinicas-ip"
    networking.gke.io/managed-certificates: "historia-clinicas-ssl"
    kubernetes.io/ingress.allow-http: "false"
    ingress.gcp.kubernetes.io/backend-protocol: '{"historia-clinicas-service":"HTTP"}'
spec:
  rules:
  - host: hc.yo-soy.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: historia-clinicas-service
            port:
              number: 80