apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yosoy-historia-clinica-ingress-nginx
  namespace: yosoy-historia-clinica
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
  - hosts:
    - hc.yo-soy.co
    secretName: hc-yo-soy-tls
  rules:
  - host: hc.yo-soy.co
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: yosoy-historia-clinica-backend-service
            port:
              number: 3001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yosoy-historia-clinica-service-simple
            port:
              number: 80