apiVersion: v1
kind: Namespace
metadata:
  name: yosoy-historia-clinica
  labels:
    name: yosoy-historia-clinica
    app.kubernetes.io/name: yosoy-historia-clinica
    app.kubernetes.io/part-of: yosoy