apiVersion: v1
kind: Service
metadata:
  name: yosoy-backend-service
  namespace: yosoy-historia-clinica
  labels:
    app: yosoy-backend
spec:
  selector:
    app: yosoy-backend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: yosoy-frontend-service
  namespace: yosoy-historia-clinica
  labels:
    app: yosoy-frontend
spec:
  selector:
    app: yosoy-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP