apiVersion: v1
kind: Namespace
metadata:
  name: authenticfarma-candidatos
  labels:
    app.kubernetes.io/name: authenticfarma-candidatos
    app.kubernetes.io/managed-by: argocd
    platform: authenticfarma
    app: candidatos