apiVersion: v1
kind: ServiceAccount
metadata:
  name: authenticfarma-candidatos-sa
  namespace: authenticfarma-candidatos
  annotations:
    iam.gke.io/gcp-service-account: authentic-candidatos-gsa@authentic-prod-464216.iam.gserviceaccount.com
  labels:
    app: authenticfarma-candidatos
    platform: authenticfarma