apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: laravel-secrets
  namespace: authenticfarma-candidatos
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: gcp-secrets
    kind: ClusterSecretStore
  target:
    name: laravel-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: authentic-candidatos-APP_KEY
    - secretKey: DB_PASSWORD
      remoteRef:
        key: authentic-candidatos-DB_PASSWORD
    - secretKey: DB_USERNAME
      remoteRef:
        key: authentic-candidatos-DB_USERNAME
    - secretKey: MAIL_USERNAME
      remoteRef:
        key: authentic-candidatos-MAIL_USERNAME
    - secretKey: MAIL_PASSWORD
      remoteRef:
        key: authentic-candidatos-MAIL_PASSWORD
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: authentic-candidatos-GOOGLE_CLIENT_SECRET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vertex-ai-secrets
  namespace: authenticfarma-candidatos
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: gcp-secrets
    kind: ClusterSecretStore
  target:
    name: vertex-ai-secrets
    creationPolicy: Owner
  data:
    - secretKey: credentials-json
      remoteRef:
        key: vertex-ai-production
