apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secrets
spec:
  provider:
    gcpsm:
      projectID: authentic-prod-464216
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-secret-manager-creds
            key: key.json
            namespace: external-secrets
      # opcional: define el tipo de autenticaci√≥n, por defecto serviceAccount
      # impersonateServiceAccount: <service-account-email>
