apiVersion: v1
kind: Pod
metadata:
  name: mysql-client-test
  namespace: authenticfarma-candidatos
spec:
  containers:
  - name: mysql-client
    image: mysql:8
    command: ["sleep", "3600"]
  restartPolicy: Never
