apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authenticfarma-candidatos
  namespace: argocd
  labels:
    platform: authenticfarma
    app: candidatos
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: authenticfarma
  source:
    repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
    targetRevision: HEAD
    path: platforms/authenticfarma/candidatos/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: authenticfarma-candidatos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authenticfarma-inventario
  namespace: argocd
  labels:
    platform: authenticfarma
    app: inventario
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: authenticfarma
  source:
    repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
    targetRevision: HEAD
    path: platforms/authenticfarma/inventario/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: authenticfarma-inventario
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authenticfarma-ventas
  namespace: argocd
  labels:
    platform: authenticfarma
    app: ventas
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: authenticfarma
  source:
    repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
    targetRevision: HEAD
    path: platforms/authenticfarma/ventas/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: authenticfarma-ventas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10