apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"labels":{"app":"authenticfarma-candidatos","platform":"authenticfarma"},"name":"authenticfarma-candidatos","namespace":"argocd"},"spec":{"destination":{"namespace":"authenticfarma-candidatos","server":"https://kubernetes.default.svc"},"project":"default","revisionHistoryLimit":3,"source":{"path":"apps/authenticfarma/candidatos/Kubernetes","repoURL":"https://github.com/desarrolloIngenios/authentic-platform.git","targetRevision":"dev"},"syncPolicy":{"automated":{"allowEmpty":false,"prune":true,"selfHeal":true},"retry":{"backoff":{"duration":"5s","factor":2,"maxDuration":"3m"},"limit":5},"syncOptions":["CreateNamespace=true","PrunePropagationPolicy=foreground","PruneLast=true"]}}}
    creationTimestamp: "2025-11-06T16:01:23Z"
    generation: 960
    labels:
      app: authenticfarma-candidatos
      platform: authenticfarma
    name: authenticfarma-candidatos
    namespace: argocd
    resourceVersion: "1762620493159359014"
    uid: a5879fce-d270-41ff-a5a7-039e4983d973
  spec:
    destination:
      namespace: authenticfarma-candidatos
      server: https://kubernetes.default.svc
    project: default
    revisionHistoryLimit: 3
    source:
      path: apps/authenticfarma/candidatos/Kubernetes
      repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
      targetRevision: dev
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      retry:
        backoff:
          duration: 5s
          factor: 2
          maxDuration: 3m
        limit: 5
      syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  status:
    controllerNamespace: argocd
    health:
      lastTransitionTime: "2025-11-06T16:50:56Z"
      status: Healthy
    history:
    - deployStartedAt: "2025-11-06T16:01:24Z"
      deployedAt: "2025-11-06T16:02:35Z"
      id: 0
      initiatedBy:
        automated: true
      revision: 4b54674eeb17477fda0ce474082a5d54e7f367db
      source:
        path: apps/authenticfarma/candidatos/Kubernetes
        repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
        targetRevision: dev
    - deployStartedAt: "2025-11-06T16:08:20Z"
      deployedAt: "2025-11-06T16:08:21Z"
      id: 1
      initiatedBy:
        automated: true
      revision: c4eb6b813eb2d523c1b503deaab47889c485334a
      source:
        path: apps/authenticfarma/candidatos/Kubernetes
        repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
        targetRevision: dev
    - deployStartedAt: "2025-11-06T16:14:28Z"
      deployedAt: "2025-11-06T16:14:29Z"
      id: 2
      initiatedBy:
        automated: true
      revision: 4de113ac07b8a4d5954d3d6259745f80c68be247
      source:
        path: apps/authenticfarma/candidatos/Kubernetes
        repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
        targetRevision: dev
    operationState:
      finishedAt: "2025-11-06T16:14:29Z"
      message: successfully synced (all tasks run)
      operation:
        initiatedBy:
          automated: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
          limit: 5
        sync:
          prune: true
          revision: 4de113ac07b8a4d5954d3d6259745f80c68be247
          syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
      phase: Succeeded
      startedAt: "2025-11-06T16:14:28Z"
      syncResult:
        resources:
        - group: apps
          hookPhase: Running
          images:
          - gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
          - us-central1-docker.pkg.dev/authentic-prod-464216/authenticfarma-repo/authentic-candidatos:v4.2.0
          kind: Deployment
          message: deployment.apps/authenticfarma-candidatos configured
          name: authenticfarma-candidatos
          namespace: authenticfarma-candidatos
          status: Synced
          syncPhase: Sync
          version: v1
        revision: 4de113ac07b8a4d5954d3d6259745f80c68be247
        source:
          path: apps/authenticfarma/candidatos/Kubernetes
          repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
          targetRevision: dev
    reconciledAt: "2025-11-08T16:48:13Z"
    resourceHealthSource: appTree
    resources:
    - group: apps
      kind: Deployment
      name: authenticfarma-candidatos
      namespace: authenticfarma-candidatos
      status: Synced
      version: v1
    sourceHydrator: {}
    sourceType: Kustomize
    summary:
      images:
      - gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
      - us-central1-docker.pkg.dev/authentic-prod-464216/authenticfarma-repo/authentic-candidatos:v4.2.0
    sync:
      comparedTo:
        destination:
          namespace: authenticfarma-candidatos
          server: https://kubernetes.default.svc
        source:
          path: apps/authenticfarma/candidatos/Kubernetes
          repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
          targetRevision: dev
      revision: f0cae3855ad56d9c9cd1474c36eec4c2c4c17995
      status: Synced
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"yosoy-historia-clinica","app.kubernetes.io/part-of":"yosoy"},"name":"yosoy-historia-clinica","namespace":"argocd"},"spec":{"destination":{"namespace":"yosoy-historia-clinica","server":"https://kubernetes.default.svc"},"project":"default","source":{"path":"infra/k8s-manifests/apps/yosoy-historia-clinica","repoURL":"https://github.com/desarrolloIngenios/authentic-platform.git","targetRevision":"dev"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"retry":{"backoff":{"duration":"5s","factor":2,"maxDuration":"3m"},"limit":5},"syncOptions":["CreateNamespace=true"]}}}
    creationTimestamp: "2025-11-08T02:17:27Z"
    generation: 416
    labels:
      app.kubernetes.io/name: yosoy-historia-clinica
      app.kubernetes.io/part-of: yosoy
    name: yosoy-historia-clinica
    namespace: argocd
    resourceVersion: "1762620482017023010"
    uid: bf459c04-40e7-4c42-8f13-c378aede8da1
  spec:
    destination:
      namespace: yosoy-historia-clinica
      server: https://kubernetes.default.svc
    project: default
    source:
      path: infra/k8s-manifests/apps/yosoy-historia-clinica
      repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
      targetRevision: dev
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      retry:
        backoff:
          duration: 5s
          factor: 2
          maxDuration: 3m
        limit: 5
      syncOptions:
      - CreateNamespace=true
  status:
    controllerNamespace: argocd
    health:
      lastTransitionTime: "2025-11-08T02:22:01Z"
      status: Degraded
    history:
    - deployStartedAt: "2025-11-08T11:02:45Z"
      deployedAt: "2025-11-08T11:02:46Z"
      id: 0
      initiatedBy:
        automated: true
      revision: f2a4e6926112c7d929ce783181327f623ae00cf7
      source:
        path: infra/k8s-manifests/apps/yosoy-historia-clinica
        repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
        targetRevision: dev
    - deployStartedAt: "2025-11-08T14:56:49Z"
      deployedAt: "2025-11-08T14:56:50Z"
      id: 1
      initiatedBy:
        automated: true
      revision: e4f480b9c4a8d87c79a264ea83a5113c0bfeec78
      source:
        path: infra/k8s-manifests/apps/yosoy-historia-clinica
        repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
        targetRevision: dev
    - deployStartedAt: "2025-11-08T16:04:05Z"
      deployedAt: "2025-11-08T16:04:06Z"
      id: 2
      initiatedBy:
        automated: true
      revision: c5bb724348a88e8c368be40c17cf05553f6b96e5
      source:
        path: infra/k8s-manifests/apps/yosoy-historia-clinica
        repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
        targetRevision: dev
    operationState:
      finishedAt: "2025-11-08T16:31:27Z"
      message: successfully synced (all tasks run)
      operation:
        initiatedBy:
          automated: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
          limit: 5
        sync:
          autoHealAttemptsCount: 1
          prune: true
          resources:
          - group: apps
            kind: Deployment
            name: yosoy-historia-clinica-backend
          revision: c5bb724348a88e8c368be40c17cf05553f6b96e5
          syncOptions:
          - CreateNamespace=true
      phase: Succeeded
      startedAt: "2025-11-08T16:31:26Z"
      syncResult:
        resources:
        - group: apps
          hookPhase: Running
          images:
          - gcr.io/authentic-prod-464216/yosoy-hc-backend:v3
          kind: Deployment
          message: deployment.apps/yosoy-historia-clinica-backend configured
          name: yosoy-historia-clinica-backend
          namespace: yosoy-historia-clinica
          status: Synced
          syncPhase: Sync
          version: v1
        revision: c5bb724348a88e8c368be40c17cf05553f6b96e5
        source:
          path: infra/k8s-manifests/apps/yosoy-historia-clinica
          repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
          targetRevision: dev
    reconciledAt: "2025-11-08T16:48:01Z"
    resourceHealthSource: appTree
    resources:
    - kind: ConfigMap
      name: yosoy-backend-real-schema
      namespace: yosoy-historia-clinica
      status: Synced
      version: v1
    - kind: Namespace
      name: yosoy-historia-clinica
      status: Synced
      version: v1
    - kind: Service
      name: yosoy-historia-clinica-backend-service
      namespace: yosoy-historia-clinica
      status: Synced
      version: v1
    - kind: Service
      name: yosoy-historia-clinica-service
      namespace: yosoy-historia-clinica
      status: Synced
      version: v1
    - kind: Service
      name: yosoy-historia-clinica-service-simple
      namespace: yosoy-historia-clinica
      status: Synced
      version: v1
    - group: apps
      kind: Deployment
      name: yosoy-historia-clinica-backend
      namespace: yosoy-historia-clinica
      status: Synced
      version: v1
    - group: apps
      kind: Deployment
      name: yosoy-historia-clinica-frontend
      namespace: yosoy-historia-clinica
      status: Synced
      version: v1
    - group: apps
      kind: Deployment
      name: yosoy-historia-clinica-frontend-simple
      namespace: yosoy-historia-clinica
      status: Synced
      version: v1
    - group: networking.k8s.io
      kind: Ingress
      name: yosoy-historia-clinica-ingress-nginx
      namespace: yosoy-historia-clinica
      status: Synced
      version: v1
    sourceHydrator: {}
    sourceType: Kustomize
    summary:
      externalURLs:
      - https://hc.yo-soy.co/
      - https://hc.yo-soy.co/api
      images:
      - gcr.io/authentic-prod-464216/yosoy-hc-backend:v3
      - gcr.io/authentic-prod-464216/yosoy-hc-frontend-simple:latest
      - gcr.io/authentic-prod-464216/yosoy-hc-frontend:latest
      - gcr.io/authentic-prod-464216/yosoy-historia-clinica:v7-dra-anamaria
      - nginx:alpine
    sync:
      comparedTo:
        destination:
          namespace: yosoy-historia-clinica
          server: https://kubernetes.default.svc
        source:
          path: infra/k8s-manifests/apps/yosoy-historia-clinica
          repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
          targetRevision: dev
      revision: f0cae3855ad56d9c9cd1474c36eec4c2c4c17995
      status: Synced
kind: List
metadata:
  resourceVersion: ""
