apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moodle
  namespace: moodle
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
    - host: e-leraning.authenticfarma.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: moodle
                port:
                  number: 80
