apiVersion: v1
kind: Service
metadata:
  name: moodle
  namespace: moodle
spec:
  selector:
    app: moodle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  externalTrafficPolicy: Local
---
image: us-central1-docker.pkg.dev/authentic-prod-464216/e-learning/moodle:latest
