apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moodle-elearning
  namespace: moodle-elearning
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: moodle-elearning.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moodle-elearning
                port:
                  number: 80
