apiVersion: v1
kind: Service
metadata:
  name: moodle-elearning
  namespace: moodle-elearning
spec:
  selector:
    app: moodle-elearning
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
