apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: isyours-ecommerce
  namespace: argocd
  labels:
    platform: isyours
    app: ecommerce
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: isyours
  source:
    repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
    targetRevision: HEAD
    path: platforms/isyours/ecommerce/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: isyours-ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: isyours-propiedades
  namespace: argocd
  labels:
    platform: isyours
    app: propiedades
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: isyours
  source:
    repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
    targetRevision: HEAD
    path: platforms/isyours/propiedades/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: isyours-propiedades
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: isyours-pagos
  namespace: argocd
  labels:
    platform: isyours
    app: pagos
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: isyours
  source:
    repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
    targetRevision: HEAD
    path: platforms/isyours/pagos/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: isyours-pagos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10