apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yosoy-historia-clinica-ingress-nginx
  namespace: yosoy-historia-clinica
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - hc.yo-soy.co
    secretName: hc-yo-soy-tls
  rules:
  - host: hc.yo-soy.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yosoy-historia-clinica-service
            port:
              number: 80