apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - services.yaml
  - ingress.yaml
  - configmap.yaml
  - pvc.yaml

labels:
- pairs:
    app.kubernetes.io/name: yosoy-historia-clinica
    app.kubernetes.io/part-of: yosoy
    app.kubernetes.io/managed-by: argocd

namespace: yosoy-historia-clinica