apiVersion: v1
kind: Service
metadata:
  name: yosoy-historia-clinica-backend-service
  namespace: yosoy-historia-clinica
spec:
  selector:
    app: yosoy-historia-clinica-backend
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: yosoy-historia-clinica-service
  namespace: yosoy-historia-clinica
spec:
  selector:
    app: yosoy-historia-clinica-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: yosoy-historia-clinica-service-simple
  namespace: yosoy-historia-clinica
spec:
  selector:
    app: yosoy-historia-clinica-frontend-simple
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP