apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yosoy-historia-clinica
  namespace: argocd
  labels:
    platform: yosoy
    app: historia-clinica
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: yosoy
  source:
    repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
    targetRevision: HEAD
    path: platforms/yosoy/historia-clinica/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: yosoy-historia-clinica
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yosoy-fitness
  namespace: argocd
  labels:
    platform: yosoy
    app: fitness
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: yosoy
  source:
    repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
    targetRevision: HEAD
    path: platforms/yosoy/fitness/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: yosoy-fitness
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yosoy-nutricion
  namespace: argocd
  labels:
    platform: yosoy
    app: nutricion
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: yosoy
  source:
    repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
    targetRevision: HEAD
    path: platforms/yosoy/nutricion/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: yosoy-nutricion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10